//! Database migration system
//!
//! Handles schema versioning and incremental migrations.
//! Version 1 is the initial schema - future migrations will be added here.

use sqlx::SqlitePool;

use super::error::SqliteError;
use super::schema::{SCHEMA, SCHEMA_VERSION};
use crate::utils::crypto::sha256_hex;

/// Run all pending migrations
pub async fn run_migrations(pool: &SqlitePool) -> Result<(), SqliteError> {
    // Check if this is a fresh database
    let table_exists: bool = sqlx::query_scalar(
        "SELECT COUNT(*) > 0 FROM sqlite_master WHERE type='table' AND name='schema_version'",
    )
    .fetch_one(pool)
    .await?;

    if !table_exists {
        tracing::debug!(
            "Initializing database with schema version {}",
            SCHEMA_VERSION
        );
        apply_initial_schema(pool).await?;
        return Ok(());
    }

    // Get current version
    let current_version: i32 =
        sqlx::query_scalar("SELECT version FROM schema_version WHERE id = 1")
            .fetch_optional(pool)
            .await?
            .unwrap_or(0);

    if current_version >= SCHEMA_VERSION {
        tracing::debug!(
            "Database schema is up to date (version {})",
            current_version
        );
        return Ok(());
    }

    // Apply incremental migrations
    for version in (current_version + 1)..=SCHEMA_VERSION {
        tracing::debug!("Applying migration to version {}", version);
        apply_migration(pool, version).await?;
    }

    Ok(())
}

/// Apply the initial schema (version 1)
async fn apply_initial_schema(pool: &SqlitePool) -> Result<(), SqliteError> {
    let start = std::time::Instant::now();

    let mut tx = pool.begin().await?;

    sqlx::query(SCHEMA).execute(&mut *tx).await?;

    // Record version
    let now = chrono::Utc::now().timestamp_nanos_opt().unwrap_or(0);
    sqlx::query(
        "INSERT INTO schema_version (id, version, applied_at, description) VALUES (1, ?, ?, 'Initial schema')",
    )
    .bind(SCHEMA_VERSION)
    .bind(now)
    .execute(&mut *tx)
    .await?;

    // Record migration
    let checksum = sha256_hex(SCHEMA);
    let elapsed_ms = start.elapsed().as_millis() as i64;
    sqlx::query(
        "INSERT INTO schema_migrations (version, name, applied_at, checksum, execution_time_ms, success) VALUES (?, ?, ?, ?, ?, 1)",
    )
    .bind(SCHEMA_VERSION)
    .bind("initial_schema")
    .bind(now)
    .bind(&checksum)
    .bind(elapsed_ms)
    .execute(&mut *tx)
    .await?;

    tx.commit().await?;

    tracing::debug!("Applied initial schema in {}ms", elapsed_ms);
    Ok(())
}

/// Apply a specific migration version
const MIGRATION_V2: &str = "ALTER TABLE files ADD COLUMN hash_algo TEXT NOT NULL DEFAULT 'sha256'";

const MIGRATION_V3: &str = r#"
CREATE TABLE IF NOT EXISTS credentials (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    provider_key TEXT NOT NULL,
    display_name TEXT NOT NULL CHECK(length(display_name) >= 1 AND length(display_name) <= 100),
    endpoint_url TEXT,
    extra_config TEXT,
    key_preview TEXT,
    created_by TEXT REFERENCES users(id) ON DELETE SET NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_creds_org ON credentials(organization_id);
CREATE INDEX IF NOT EXISTS idx_creds_org_key ON credentials(organization_id, provider_key);
CREATE TABLE IF NOT EXISTS credential_project_permissions (
    id TEXT PRIMARY KEY,
    credential_id TEXT NOT NULL REFERENCES credentials(id) ON DELETE CASCADE,
    organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    project_id TEXT REFERENCES projects(id) ON DELETE CASCADE,
    access TEXT NOT NULL DEFAULT 'allow' CHECK(access IN ('allow', 'deny')),
    created_by TEXT REFERENCES users(id) ON DELETE SET NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_cred_perms_credential ON credential_project_permissions(credential_id);
CREATE INDEX IF NOT EXISTS idx_cred_perms_project ON credential_project_permissions(project_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_cred_perms_unique_project
    ON credential_project_permissions(credential_id, project_id)
    WHERE project_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_cred_perms_unique_org_default
    ON credential_project_permissions(credential_id)
    WHERE project_id IS NULL;
"#;

/// `trace_files` is keyed by `(trace_id, file_hash)`, which omits the project.
///
/// A trace id is generated by the client, so two projects can present the same one - and then one
/// project's association silently satisfies `INSERT OR IGNORE` for the other, leaving the second
/// project's file with no association and a reference count that nothing will ever release. Widening
/// the key needs a table rebuild, because SQLite cannot alter a primary key in place.
///
/// The copy is keyed on the widened primary key, so any rows that had already collided are collapsed
/// rather than duplicated - which is the pre-existing state, not something this introduces.
const MIGRATION_V4: &str = r#"
CREATE TABLE trace_files_v4 (
    trace_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    file_hash TEXT NOT NULL,
    PRIMARY KEY (project_id, trace_id, file_hash),
    FOREIGN KEY (project_id, file_hash) REFERENCES files(project_id, file_hash) ON DELETE CASCADE
);
INSERT OR IGNORE INTO trace_files_v4 (trace_id, project_id, file_hash)
    SELECT trace_id, project_id, file_hash FROM trace_files;
DROP TABLE trace_files;
ALTER TABLE trace_files_v4 RENAME TO trace_files;
CREATE INDEX IF NOT EXISTS idx_trace_files_trace ON trace_files(trace_id);
CREATE INDEX IF NOT EXISTS idx_trace_files_project ON trace_files(project_id);
CREATE INDEX IF NOT EXISTS idx_trace_files_project_hash ON trace_files(project_id, file_hash);
"#;

/// A durable fence for file deletion.
///
/// Deleting the metadata row and then the bytes is not enough: ingestion can recreate the row, write an
/// association and finalise the bytes in that window, and then the byte delete removes content a
/// committed row references. The count cannot express "deletion in progress" - only a claim can.
///
/// `deleting_at` is that claim. Cleanup sets it before touching storage; association refuses while it
/// is set, which refuses the batch and lets the exporter retry once deletion has finished.
const MIGRATION_V5: &str = "ALTER TABLE files ADD COLUMN deleting_at INTEGER";

/// The same fence for a project, which needs it more than a file does.
///
/// Deleting a project touches four stores - analytics rows, file bytes, file rows, the project row -
/// with no transaction spanning them, and it used to delete the data first and the row last. So for
/// the whole of it the project was live: readable, and ingestible. Spans arriving in that window were
/// written *after* their analytics rows had been deleted and survived the whole cleanup, attached to a
/// project id that then had no row at all - invisible to every read path, and inherited by the next
/// project created with the same id.
///
/// `deleting_at` states the intent before any of it starts. Reads treat a claimed project as absent,
/// ingestion refuses it, and the row is removed only once the data is verified gone - so the row's
/// disappearance is the *last* fact, not the first.
const MIGRATION_V6: &str = "ALTER TABLE projects ADD COLUMN deleting_at INTEGER";

/// Removal driven by what has been observed, not by how long ago the deletion started.
///
/// The project tombstone was removed once its claim was older than a wall-clock grace period, and that
/// is not a bound: a writer that read the fence before the claim can commit arbitrarily later - a stalled
/// blocking insert, a retrying object store, a paused container - and the row it needs to be collected by
/// would already be gone. `clean_sweeps` counts consecutive sweeps that found nothing, so the row goes on
/// the strength of repeated observation instead.
///
/// Organizations get the same tombstone, because deleting an organization row cascades its project rows
/// away - and those rows *are* the projects' tombstones, so removing it early stops exactly the cleanup
/// that collects a late write.
const MIGRATION_V8: &str = r#"ALTER TABLE projects ADD COLUMN clean_sweeps INTEGER NOT NULL DEFAULT 0;
ALTER TABLE organizations ADD COLUMN deleting_at INTEGER;
"#;

/// The clean-sweep count has to measure elapsed observation, not sweeps.
///
/// Every instance of a horizontally scaled deployment runs the sweep, and the count was a bare increment -
/// so five instances reached five "consecutive clean sweeps" inside a single interval, and the barrier
/// grew weaker the more instances you ran. `last_sweep_at` makes the increment conditional on a window
/// having passed, and since it is one atomic UPDATE, concurrent instances race for the row and only one
/// wins per window.
const MIGRATION_V9: &str = "ALTER TABLE projects ADD COLUMN last_sweep_at INTEGER";

/// Cleanup that stays discoverable after the project row is gone.
///
/// A tombstone removed on finite evidence still loses to an arbitrarily delayed writer: one that read the
/// fence before the tombstone can commit after the row is removed, and with the row goes every trace of
/// the project having existed. This table is that trace. The sweep keeps collecting rows that appear for a
/// deleted id, so the residual stops being "ten minutes" and becomes the retention.
const MIGRATION_V10: &str = r#"CREATE TABLE IF NOT EXISTS deleted_projects (
    project_id TEXT PRIMARY KEY,
    deleted_at INTEGER NOT NULL
);
"#;

/// One check per deleted id per window, rather than one per instance per sweep.
///
/// The records are kept forever - any retention is a bound on how late a stalled writer may commit - so
/// scanning all of them every sweep on every instance is work proportional to instances times lifetime
/// deletions. Claiming the check by moving `last_checked_at` forward makes the cost independent of the
/// instance count.
const MIGRATION_V11: &str = "ALTER TABLE deleted_projects ADD COLUMN last_checked_at INTEGER";

/// Bounded, indexed, backed-off discovery for permanent deletion records.
///
/// Keeping the records forever is the right correctness choice, but re-checking every one of them at the
/// same rate is unbounded lifetime work: a hundred thousand historical deletions meant a hundred thousand
/// storage listings per window, forever, plus an unindexed scan to find them. `quiet_checks` pushes each
/// successive check further out, and the index makes finding the due ones cheap.
const MIGRATION_V12: &str = r#"ALTER TABLE deleted_projects ADD COLUMN quiet_checks INTEGER NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS idx_deleted_projects_next_check ON deleted_projects(last_checked_at);
"#;

/// Index the due time itself, not an input to it.
///
/// Eligibility was `last_checked_at <= now - base * 2^quiet_checks`, and an index on `last_checked_at`
/// alone bounds the rows *returned* rather than the rows examined - so with many heavily backed-off records
/// the planner still walks a large part of a table that only grows. `next_check_at` is materialised on every
/// check and indexed, which makes the search bounded.
const MIGRATION_V13: &str = r#"ALTER TABLE deleted_projects ADD COLUMN next_check_at INTEGER;
UPDATE deleted_projects SET next_check_at = COALESCE(last_checked_at, deleted_at);
CREATE INDEX IF NOT EXISTS idx_deleted_projects_due ON deleted_projects(next_check_at);
"#;

/// An owned claim, and a due time that is never null.
///
/// Two defects. Reporting a check was an unconditional update by project id, so a worker whose lease expired
/// part way through its batch could overwrite the schedule *and the result* of the worker that had since
/// taken the id - and then a third could claim it while the second was still working. A claim now carries a
/// token and a report matches on it.
///
/// And `next_check_at` was nullable, which PostgreSQL sorts *last* while SQLite sorts nulls first - so on
/// PostgreSQL a freshly deleted project queued behind every overdue record, hours or days on a backlog, with
/// its late files and rows hidden the whole time.
/// SQLite cannot add a NOT NULL constraint to an existing column, so the table is rebuilt.
///
/// Backfilling the values and stopping there left an upgraded database with a *nullable* `next_check_at`
/// while a fresh one declares it NOT NULL - two different schemas for the same version. Nothing in the code
/// inserts a null today, but the eligibility test is `next_check_at <= unixepoch()`, which no null ever
/// satisfies: one row inserted by a future path, or by hand, would go unclaimed forever and its project's
/// late data undiscovered. A declared invariant that only the fresh schema enforces is not an invariant.
const MIGRATION_V14: &str = r#"CREATE TABLE deleted_projects_v14 (
    project_id TEXT PRIMARY KEY,
    deleted_at INTEGER NOT NULL,
    last_checked_at INTEGER,
    quiet_checks INTEGER NOT NULL DEFAULT 0,
    next_check_at INTEGER NOT NULL DEFAULT 0,
    claim_token INTEGER NOT NULL DEFAULT 0
);
INSERT INTO deleted_projects_v14 (project_id, deleted_at, last_checked_at, quiet_checks, next_check_at)
SELECT project_id, deleted_at, last_checked_at, quiet_checks,
       COALESCE(next_check_at, last_checked_at, deleted_at)
FROM deleted_projects;
DROP TABLE deleted_projects;
ALTER TABLE deleted_projects_v14 RENAME TO deleted_projects;
CREATE INDEX IF NOT EXISTS idx_deleted_projects_due ON deleted_projects(next_check_at);
"#;

async fn apply_migration(pool: &SqlitePool, version: i32) -> Result<(), SqliteError> {
    match version {
        1 => {
            // Already handled by initial schema
            Ok(())
        }
        2 => apply_versioned_migration(pool, 2, "add_hash_algo_to_files", MIGRATION_V2).await,
        3 => apply_versioned_migration(pool, 3, "add_credentials_tables", MIGRATION_V3).await,
        4 => apply_versioned_migration(pool, 4, "project_scoped_trace_files", MIGRATION_V4).await,
        5 => apply_versioned_migration(pool, 5, "file_deletion_fence", MIGRATION_V5).await,
        6 => apply_versioned_migration(pool, 6, "project_deletion_fence", MIGRATION_V6).await,
        // 7 is the PostgreSQL-only widening of the file counters; SQLite's INTEGER is already 64-bit.
        7 => Ok(()),
        8 => apply_versioned_migration(pool, 8, "deletion_tombstones", MIGRATION_V8).await,
        9 => apply_versioned_migration(pool, 9, "sweep_windows", MIGRATION_V9).await,
        10 => apply_versioned_migration(pool, 10, "deleted_projects", MIGRATION_V10).await,
        11 => apply_versioned_migration(pool, 11, "deleted_project_windows", MIGRATION_V11).await,
        12 => apply_versioned_migration(pool, 12, "deleted_project_backoff", MIGRATION_V12).await,
        13 => apply_versioned_migration(pool, 13, "deleted_project_due_index", MIGRATION_V13).await,
        14 => {
            apply_versioned_migration(pool, 14, "deleted_project_claim_token", MIGRATION_V14).await
        }
        _ => Err(SqliteError::MigrationFailed {
            version,
            name: "unknown".to_string(),
            error: format!("Unknown migration version: {}", version),
        }),
    }
}

/// Apply a versioned migration with tracking
async fn apply_versioned_migration(
    pool: &SqlitePool,
    version: i32,
    name: &str,
    sql: &str,
) -> Result<(), SqliteError> {
    let start = std::time::Instant::now();

    let mut tx = pool.begin().await?;

    // One script, not statements split on `;`. A semicolon inside a `--` comment or a string literal
    // ends a "statement" mid-construct, and the fragment is then rejected as a syntax error - which is
    // exactly what happened to the PostgreSQL twin's initial schema, where it meant no fresh database
    // could be created at all.
    sqlx::raw_sql(sql)
        .execute(&mut *tx)
        .await
        .map_err(|e| SqliteError::MigrationFailed {
            version,
            name: name.to_string(),
            error: e.to_string(),
        })?;

    // Update version
    let now = chrono::Utc::now().timestamp_nanos_opt().unwrap_or(0);
    sqlx::query(
        "UPDATE schema_version SET version = ?, applied_at = ?, description = ? WHERE id = 1",
    )
    .bind(version)
    .bind(now)
    .bind(name)
    .execute(&mut *tx)
    .await?;

    // Record migration
    let checksum = sha256_hex(sql);
    let elapsed_ms = start.elapsed().as_millis() as i64;
    sqlx::query(
        "INSERT INTO schema_migrations (version, name, applied_at, checksum, execution_time_ms, success) VALUES (?, ?, ?, ?, ?, 1)",
    )
    .bind(version)
    .bind(name)
    .bind(now)
    .bind(&checksum)
    .bind(elapsed_ms)
    .execute(&mut *tx)
    .await?;

    tx.commit().await?;

    tracing::debug!(
        "Applied migration v{} ({}) in {}ms",
        version,
        name,
        elapsed_ms
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// An upgraded database has the same schema as a fresh one.
    ///
    /// This is the invariant a migration exists to preserve, and it is easy to half-keep: SQLite cannot add
    /// a NOT NULL constraint with `ALTER TABLE`, so a migration that backfills values and stops leaves the
    /// column nullable while the fresh schema declares it NOT NULL. Two schemas for one version, and the
    /// difference only shows when something inserts the null that the fresh schema would have refused.
    ///
    /// Checked by comparing what SQLite itself reports about the columns, so it covers any future migration
    /// that alters a table rather than only the one that prompted it.
    #[tokio::test]
    async fn an_upgraded_schema_matches_a_fresh_one() {
        async fn columns(
            pool: &SqlitePool,
            table: &str,
        ) -> Vec<(String, String, i64, Option<String>)> {
            let mut rows: Vec<(String, String, i64, Option<String>)> = sqlx::query_as(&format!(
                "SELECT name, type, \"notnull\", dflt_value FROM pragma_table_info('{table}')"
            ))
            .fetch_all(pool)
            .await
            .expect("pragma");
            rows.sort();
            rows
        }

        // A fresh database at the current version.
        let fresh = SqlitePool::connect(":memory:").await.expect("fresh pool");
        sqlx::raw_sql(SCHEMA)
            .execute(&fresh)
            .await
            .expect("fresh schema");

        // An old database, walked forward by the migration runner. Version 10 is where `deleted_projects`
        // first appears, so the walk covers every change made to it since.
        let upgraded = SqlitePool::connect(":memory:")
            .await
            .expect("upgraded pool");
        sqlx::raw_sql(
            "CREATE TABLE schema_version (id INTEGER PRIMARY KEY, version INTEGER NOT NULL, \
             applied_at INTEGER NOT NULL, description TEXT);
             INSERT INTO schema_version (id, version, applied_at) VALUES (1, 10, 0);
             CREATE TABLE schema_migrations (version INTEGER PRIMARY KEY, name TEXT NOT NULL, \
                 applied_at INTEGER NOT NULL, checksum TEXT NOT NULL, execution_time_ms INTEGER, \
                 success INTEGER NOT NULL DEFAULT 1);
             CREATE TABLE deleted_projects (project_id TEXT PRIMARY KEY, deleted_at INTEGER NOT NULL);
             INSERT INTO deleted_projects (project_id, deleted_at) VALUES ('legacy', 1000);",
        )
        .execute(&upgraded)
        .await
        .expect("legacy shape");
        for version in 11..=SCHEMA_VERSION {
            apply_migration(&upgraded, version)
                .await
                .unwrap_or_else(|e| panic!("migration {version}: {e}"));
        }

        assert_eq!(
            columns(&upgraded, "deleted_projects").await,
            columns(&fresh, "deleted_projects").await,
            "an upgraded database's `deleted_projects` differs from a fresh one's, so the invariant the \\
             fresh schema declares is not enforced after an upgrade"
        );

        // And the legacy row came through with a due time rather than a null, or it would never be claimed.
        let due: (Option<i64>,) = sqlx::query_as(
            "SELECT next_check_at FROM deleted_projects WHERE project_id = 'legacy'",
        )
        .fetch_one(&upgraded)
        .await
        .expect("legacy row");
        assert_eq!(
            due.0,
            Some(1000),
            "a legacy row must come through the upgrade with a due time; a null is never claimed, so its \\
             project's late data would go uncollected forever"
        );
    }
}
