//! Database migration system
//!
//! Handles schema versioning and incremental migrations.
//! Version 1 is the initial schema - future migrations will be added here.

use sqlx::SqlitePool;

use super::error::SqliteError;
use super::schema::{SCHEMA, SCHEMA_VERSION};
use crate::utils::crypto::sha256_hex;

/// Run all pending migrations
pub async fn run_migrations(pool: &SqlitePool) -> Result<(), SqliteError> {
    // Check if this is a fresh database
    let table_exists: bool = sqlx::query_scalar(
        "SELECT COUNT(*) > 0 FROM sqlite_master WHERE type='table' AND name='schema_version'",
    )
    .fetch_one(pool)
    .await?;

    if !table_exists {
        tracing::debug!(
            "Initializing database with schema version {}",
            SCHEMA_VERSION
        );
        apply_initial_schema(pool).await?;
        return Ok(());
    }

    // Get current version
    let current_version: i32 =
        sqlx::query_scalar("SELECT version FROM schema_version WHERE id = 1")
            .fetch_optional(pool)
            .await?
            .unwrap_or(0);

    if current_version >= SCHEMA_VERSION {
        tracing::debug!(
            "Database schema is up to date (version {})",
            current_version
        );
        return Ok(());
    }

    // Apply incremental migrations
    for version in (current_version + 1)..=SCHEMA_VERSION {
        tracing::debug!("Applying migration to version {}", version);
        apply_migration(pool, version).await?;
    }

    Ok(())
}

/// Apply the initial schema (version 1)
async fn apply_initial_schema(pool: &SqlitePool) -> Result<(), SqliteError> {
    let start = std::time::Instant::now();

    let mut tx = pool.begin().await?;

    sqlx::query(SCHEMA).execute(&mut *tx).await?;

    // Record version
    let now = chrono::Utc::now().timestamp_nanos_opt().unwrap_or(0);
    sqlx::query(
        "INSERT INTO schema_version (id, version, applied_at, description) VALUES (1, ?, ?, 'Initial schema')",
    )
    .bind(SCHEMA_VERSION)
    .bind(now)
    .execute(&mut *tx)
    .await?;

    // Record migration
    let checksum = sha256_hex(SCHEMA);
    let elapsed_ms = start.elapsed().as_millis() as i64;
    sqlx::query(
        "INSERT INTO schema_migrations (version, name, applied_at, checksum, execution_time_ms, success) VALUES (?, ?, ?, ?, ?, 1)",
    )
    .bind(SCHEMA_VERSION)
    .bind("initial_schema")
    .bind(now)
    .bind(&checksum)
    .bind(elapsed_ms)
    .execute(&mut *tx)
    .await?;

    tx.commit().await?;

    tracing::debug!("Applied initial schema in {}ms", elapsed_ms);
    Ok(())
}

/// Apply a specific migration version
const MIGRATION_V2: &str = "ALTER TABLE files ADD COLUMN hash_algo TEXT NOT NULL DEFAULT 'sha256'";

const MIGRATION_V3: &str = r#"
CREATE TABLE IF NOT EXISTS credentials (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    provider_key TEXT NOT NULL,
    display_name TEXT NOT NULL CHECK(length(display_name) >= 1 AND length(display_name) <= 100),
    endpoint_url TEXT,
    extra_config TEXT,
    key_preview TEXT,
    created_by TEXT REFERENCES users(id) ON DELETE SET NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_creds_org ON credentials(organization_id);
CREATE INDEX IF NOT EXISTS idx_creds_org_key ON credentials(organization_id, provider_key);
CREATE TABLE IF NOT EXISTS credential_project_permissions (
    id TEXT PRIMARY KEY,
    credential_id TEXT NOT NULL REFERENCES credentials(id) ON DELETE CASCADE,
    organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    project_id TEXT REFERENCES projects(id) ON DELETE CASCADE,
    access TEXT NOT NULL DEFAULT 'allow' CHECK(access IN ('allow', 'deny')),
    created_by TEXT REFERENCES users(id) ON DELETE SET NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_cred_perms_credential ON credential_project_permissions(credential_id);
CREATE INDEX IF NOT EXISTS idx_cred_perms_project ON credential_project_permissions(project_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_cred_perms_unique_project
    ON credential_project_permissions(credential_id, project_id)
    WHERE project_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_cred_perms_unique_org_default
    ON credential_project_permissions(credential_id)
    WHERE project_id IS NULL;
"#;

/// `trace_files` is keyed by `(trace_id, file_hash)`, which omits the project.
///
/// A trace id is generated by the client, so two projects can present the same one - and then one
/// project's association silently satisfies `INSERT OR IGNORE` for the other, leaving the second
/// project's file with no association and a reference count that nothing will ever release. Widening
/// the key needs a table rebuild, because SQLite cannot alter a primary key in place.
///
/// The copy is keyed on the widened primary key, so any rows that had already collided are collapsed
/// rather than duplicated - which is the pre-existing state, not something this introduces.
const MIGRATION_V4: &str = r#"
CREATE TABLE trace_files_v4 (
    trace_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    file_hash TEXT NOT NULL,
    PRIMARY KEY (project_id, trace_id, file_hash),
    FOREIGN KEY (project_id, file_hash) REFERENCES files(project_id, file_hash) ON DELETE CASCADE
);
INSERT OR IGNORE INTO trace_files_v4 (trace_id, project_id, file_hash)
    SELECT trace_id, project_id, file_hash FROM trace_files;
DROP TABLE trace_files;
ALTER TABLE trace_files_v4 RENAME TO trace_files;
CREATE INDEX IF NOT EXISTS idx_trace_files_trace ON trace_files(trace_id);
CREATE INDEX IF NOT EXISTS idx_trace_files_project ON trace_files(project_id);
CREATE INDEX IF NOT EXISTS idx_trace_files_project_hash ON trace_files(project_id, file_hash);
"#;

/// A durable fence for file deletion.
///
/// Deleting the metadata row and then the bytes is not enough: ingestion can recreate the row, write an
/// association and finalise the bytes in that window, and then the byte delete removes content a
/// committed row references. The count cannot express "deletion in progress" - only a claim can.
///
/// `deleting_at` is that claim. Cleanup sets it before touching storage; association refuses while it
/// is set, which refuses the batch and lets the exporter retry once deletion has finished.
const MIGRATION_V5: &str = "ALTER TABLE files ADD COLUMN deleting_at INTEGER";

/// The same fence for a project, which needs it more than a file does.
///
/// Deleting a project touches four stores - analytics rows, file bytes, file rows, the project row -
/// with no transaction spanning them, and it used to delete the data first and the row last. So for
/// the whole of it the project was live: readable, and ingestible. Spans arriving in that window were
/// written *after* their analytics rows had been deleted and survived the whole cleanup, attached to a
/// project id that then had no row at all - invisible to every read path, and inherited by the next
/// project created with the same id.
///
/// `deleting_at` states the intent before any of it starts. Reads treat a claimed project as absent,
/// ingestion refuses it, and the row is removed only once the data is verified gone - so the row's
/// disappearance is the *last* fact, not the first.
const MIGRATION_V6: &str = "ALTER TABLE projects ADD COLUMN deleting_at INTEGER";

/// Removal driven by what has been observed, not by how long ago the deletion started.
///
/// The project tombstone was removed once its claim was older than a wall-clock grace period, and that
/// is not a bound: a writer that read the fence before the claim can commit arbitrarily later - a stalled
/// blocking insert, a retrying object store, a paused container - and the row it needs to be collected by
/// would already be gone. `clean_sweeps` counts consecutive sweeps that found nothing, so the row goes on
/// the strength of repeated observation instead.
///
/// Organizations get the same tombstone, because deleting an organization row cascades its project rows
/// away - and those rows *are* the projects' tombstones, so removing it early stops exactly the cleanup
/// that collects a late write.
const MIGRATION_V8: &str = r#"ALTER TABLE projects ADD COLUMN clean_sweeps INTEGER NOT NULL DEFAULT 0;
ALTER TABLE organizations ADD COLUMN deleting_at INTEGER;
"#;

/// The clean-sweep count has to measure elapsed observation, not sweeps.
///
/// Every instance of a horizontally scaled deployment runs the sweep, and the count was a bare increment -
/// so five instances reached five "consecutive clean sweeps" inside a single interval, and the barrier
/// grew weaker the more instances you ran. `last_sweep_at` makes the increment conditional on a window
/// having passed, and since it is one atomic UPDATE, concurrent instances race for the row and only one
/// wins per window.
const MIGRATION_V9: &str = "ALTER TABLE projects ADD COLUMN last_sweep_at INTEGER";

async fn apply_migration(pool: &SqlitePool, version: i32) -> Result<(), SqliteError> {
    match version {
        1 => {
            // Already handled by initial schema
            Ok(())
        }
        2 => apply_versioned_migration(pool, 2, "add_hash_algo_to_files", MIGRATION_V2).await,
        3 => apply_versioned_migration(pool, 3, "add_credentials_tables", MIGRATION_V3).await,
        4 => apply_versioned_migration(pool, 4, "project_scoped_trace_files", MIGRATION_V4).await,
        5 => apply_versioned_migration(pool, 5, "file_deletion_fence", MIGRATION_V5).await,
        6 => apply_versioned_migration(pool, 6, "project_deletion_fence", MIGRATION_V6).await,
        // 7 is the PostgreSQL-only widening of the file counters; SQLite's INTEGER is already 64-bit.
        7 => Ok(()),
        8 => apply_versioned_migration(pool, 8, "deletion_tombstones", MIGRATION_V8).await,
        9 => apply_versioned_migration(pool, 9, "sweep_windows", MIGRATION_V9).await,
        _ => Err(SqliteError::MigrationFailed {
            version,
            name: "unknown".to_string(),
            error: format!("Unknown migration version: {}", version),
        }),
    }
}

/// Apply a versioned migration with tracking
async fn apply_versioned_migration(
    pool: &SqlitePool,
    version: i32,
    name: &str,
    sql: &str,
) -> Result<(), SqliteError> {
    let start = std::time::Instant::now();

    let mut tx = pool.begin().await?;

    // One script, not statements split on `;`. A semicolon inside a `--` comment or a string literal
    // ends a "statement" mid-construct, and the fragment is then rejected as a syntax error - which is
    // exactly what happened to the PostgreSQL twin's initial schema, where it meant no fresh database
    // could be created at all.
    sqlx::raw_sql(sql)
        .execute(&mut *tx)
        .await
        .map_err(|e| SqliteError::MigrationFailed {
            version,
            name: name.to_string(),
            error: e.to_string(),
        })?;

    // Update version
    let now = chrono::Utc::now().timestamp_nanos_opt().unwrap_or(0);
    sqlx::query(
        "UPDATE schema_version SET version = ?, applied_at = ?, description = ? WHERE id = 1",
    )
    .bind(version)
    .bind(now)
    .bind(name)
    .execute(&mut *tx)
    .await?;

    // Record migration
    let checksum = sha256_hex(sql);
    let elapsed_ms = start.elapsed().as_millis() as i64;
    sqlx::query(
        "INSERT INTO schema_migrations (version, name, applied_at, checksum, execution_time_ms, success) VALUES (?, ?, ?, ?, ?, 1)",
    )
    .bind(version)
    .bind(name)
    .bind(now)
    .bind(&checksum)
    .bind(elapsed_ms)
    .execute(&mut *tx)
    .await?;

    tx.commit().await?;

    tracing::debug!(
        "Applied migration v{} ({}) in {}ms",
        version,
        name,
        elapsed_ms
    );
    Ok(())
}
