name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We appreciate your ideas to make SideSeat better.

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and this feature has not been requested
          required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      options:
        - New functionality
        - Enhancement to existing feature
        - Performance improvement
        - Developer experience
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What pain point are you experiencing?
      placeholder: |
        I'm frustrated when...
        Currently, I have to...
        There's no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        I would like SideSeat to...
        This could work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or workarounds have you considered?
      placeholder: |
        I've tried...
        Another approach could be...

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How many users would benefit from this feature?
      options:
        - High - Core functionality, affects most users
        - Medium - Useful for many workflows
        - Low - Nice to have, niche use case
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I'm willing to submit a PR for this feature
        - label: I can help test this feature
        - label: I can help document this feature

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any mockups, screenshots, or additional context
      placeholder: Add any other context...
