"""``python -m harness matrix``: replay a suite's scenarios against the historical releases it names.

::

    python -m harness matrix strands                      # every variant, every matrix scenario, offline
    python -m harness matrix strands 1.20.0 --scenario tool_use
    python -m harness matrix strands --census             # classify every release of the window (network)
    python -m harness matrix strands --live 1.38.0        # record a [[recording]] release's cassettes (Bedrock)
    python -m harness matrix --check                      # offline: census coverage and fixture freshness
    python -m harness matrix --list

Environments live outside the repository (``$SIDESEAT_MATRIX_CACHE``); fixtures are written to
``server/tests/fixtures/messages/<producer>/<mode>@<variant>/<scenario>/``, with the provenance of every
versioned mode in ``<producer>/versions.json``. Regenerate the expectations afterwards and read them::

    UPDATE_GOLDENS=1 cargo nextest run --locked -p sideseat-server --test message_goldens -E 'test(=message_goldens)'
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from harness import capture
from harness.matrix import census, environment
from harness.matrix.run import commit, replay
from harness.matrix.shape import digest, shape
from harness.matrix.spec import CENSUS, Matrix, Variant, load

PROVENANCE = "versions.json"
PROVENANCE_FORMAT = "sideseat.fixture-versions/1"


def matrices() -> dict[str, tuple[capture.Suite, Matrix]]:
    found = {}
    for producer, suite in sorted(capture.suites().items()):
        if suite.language == "python" and (matrix := load(suite.root)) is not None:
            found[producer] = (suite, matrix)
    return found


def fixture_dir(producer: str, mode: str, variant: Variant, scenario: str) -> Path:
    return capture.FIXTURES / producer / variant.mode(mode) / scenario


def census_of(matrix: Matrix) -> dict[str, Any] | None:
    path = matrix.suite / CENSUS
    return json.loads(path.read_text()) if path.exists() else None


def provenance(
    producer: str, matrix: Matrix, installed: dict[str, dict[str, str]]
) -> dict[str, Any]:
    """Which release, profile and environment each versioned mode of ``producer`` was recorded with."""
    path = capture.FIXTURES / producer / PROVENANCE
    previous = json.loads(path.read_text())["modes"] if path.exists() else {}
    dates = {
        (e["version"], e["profile"]): e["date"]
        for e in (census_of(matrix) or {}).get("releases", [])
    }
    modes = {}
    for variant in (v for v in matrix.variants if not v.current):
        for mode in matrix.modes:
            name = variant.mode(mode)
            entry = {
                "package": matrix.package,
                "version": variant.version,
                "profile": variant.profile,
                "env": matrix.profiles[variant.profile],
                "released": dates.get((variant.version, variant.profile)),
                "installed": installed.get(variant.name)
                or previous.get(name, {}).get("installed", {}),
            }
            if (capture.FIXTURES / producer / name).is_dir():
                modes[name] = entry
    return {
        "format": PROVENANCE_FORMAT,
        "//": "Generated by `python -m harness matrix`; do not edit.",
        "modes": modes,
    }


def tracked_packages(matrix: Matrix) -> list[str]:
    """What the support matrix row reports: the framework, its instrumentation, and OpenTelemetry."""
    project = (matrix.suite / "pyproject.toml").read_text()
    import re
    import tomllib

    names = [
        re.split(r"[\[<>=!~ ;]", requirement, maxsplit=1)[0]
        for requirement in tomllib.loads(project)["project"]["dependencies"]
    ]
    keep = [n for n in names if not n.startswith(("sideseat", "mcp"))]
    return [
        matrix.package,
        *[n for n in keep if n != matrix.package],
        "opentelemetry-sdk",
    ]


def record(
    producer: str,
    suite: capture.Suite,
    matrix: Matrix,
    names: list[str],
    scenarios: list[str],
) -> list[str]:
    failed = []
    installed: dict[str, dict[str, str]] = {}
    chosen = [matrix.variant(n) for n in names] if names else list(matrix.variants)
    # The current release's fixtures are the ordinary capture's; `capture` records them.
    chosen = [v for v in chosen if not v.current]
    dates = {
        e["version"]: e["date"] for e in (census_of(matrix) or {}).get("releases", [])
    }
    for variant in chosen:
        if matrix.era and variant.version not in dates:
            failed.append(f"{variant.name}: no release date; take the census first")
            continue
        try:
            env_path = environment.ensure(matrix, variant, dates.get(variant.version))
        except environment.UnresolvableRelease as error:
            failed.append(f"{variant.name}: {error}")
            continue
        installed[variant.name] = environment.installed(
            env_path, *tracked_packages(matrix)
        )
        for mode in matrix.modes:
            for scenario in [
                s
                for s in variant.scenarios
                if (not scenarios or s in scenarios) and s not in variant.withheld
            ]:
                label = f"{producer}/{variant.mode(mode)}/{scenario}"
                result = replay(
                    suite,
                    env_path,
                    scenario,
                    mode=mode,
                    env=matrix.profiles[variant.profile],
                    cassettes=matrix.cassettes(variant.version),
                )
                if not result.ok:
                    print(f"[matrix] {label}: FAILED - {'; '.join(result.problems)}")
                    print(result.output[-1500:], file=sys.stderr)
                    result.discard()
                    failed.append(label)
                    continue
                count = commit(result, fixture_dir(producer, mode, variant, scenario))
                print(
                    f"[matrix] {label}: {count} request(s); replay matched {result.exact} exactly, "
                    f"{result.by_order} by order"
                )
        # Rebuilt from the uv cache in seconds when next needed; kept, a window's worth is gigabytes.
        environment.remove(env_path)
    document = provenance(producer, matrix, installed)
    (capture.FIXTURES / producer / PROVENANCE).write_text(
        json.dumps(document, indent=1, ensure_ascii=False) + "\n"
    )
    return failed


def record_live(suite: capture.Suite, matrix: Matrix, versions: list[str]) -> list[str]:
    """Record the model traffic of each release in ``[[recording]]`` live, into its own cassettes.

    Every matrix scenario runs once, natively and without a profile, through the recording proxy on the
    ambient AWS credentials; the telemetry is discarded, because the fixtures are recorded afterwards
    by the ordinary offline replay of these cassettes, like every other variant's.
    """
    failed = []
    chosen = versions or sorted(matrix.recordings)
    if stray := [v for v in chosen if v not in matrix.recordings]:
        raise SystemExit(
            f"{stray}: not in [[recording]]; say why a release records its own cassettes"
        )
    dates = {
        e.version: e.date
        for e in census.releases(
            matrix.package,
            matrix.since,
            prereleases=matrix.prereleases,
            before=matrix.resolved_before,
        )
    }
    for version in chosen:
        try:
            env_path = environment.ensure_requirements(
                matrix,
                f"{matrix.suite.name}/live/{version}",
                matrix.pinned(version),
                released=dates.get(version),
            )
        except environment.UnresolvableRelease as error:
            failed.append(f"{version}: {error}")
            continue
        target = matrix.cassettes(version)
        for scenario in matrix.scenarios:
            result = replay(suite, env_path, scenario, cassettes=target, live=True)
            label = f"{suite.manifest['producer']}@{version}/{scenario}"
            if not result.ok:
                print(f"[matrix] {label}: FAILED - {'; '.join(result.problems)}")
                print(result.output[-1500:], file=sys.stderr)
                (target / f"{scenario}.json").unlink(missing_ok=True)
                failed.append(label)
            else:
                print(
                    f"[matrix] {label}: recorded live into {target.name}/{scenario}.json"
                )
            result.discard()
        environment.remove(env_path)
    return failed


def support_rows(producer: str) -> list[str]:
    """The fixtures README's support-matrix rows for every versioned mode of ``producer``."""
    path = capture.FIXTURES / producer / PROVENANCE
    if not path.exists():
        return []
    rows = []
    for mode, entry in sorted(json.loads(path.read_text())["modes"].items()):
        directory = capture.FIXTURES / producer / mode
        samples = [d for d in directory.iterdir() if d.is_dir()]
        requests = sum(len(list(d.glob("req-*"))) for d in samples)
        installed = " / ".join(
            f"{name} {version}" for name, version in entry["installed"].items()
        )
        settings = ", ".join(f"{k}={v}" for k, v in entry["env"].items())
        profile = (
            ""
            if entry["profile"] == "default"
            else f", profile `{entry['profile']}` ({settings})"
        )
        released = f", released {entry['released']}" if entry["released"] else ""
        rows.append(
            f"| `{producer}/{mode}` | {installed}{profile}{released}; version matrix variant, replayed "
            f"offline from the suite's cassettes | {len(samples)} | {requests} |"
        )
    return rows


def check(producer: str, matrix: Matrix) -> list[str]:
    """Offline: the census covers the window, and each variant's committed probe still has its shape."""
    problems = []
    document = census_of(matrix)
    if document is None:
        return [
            f"{producer}: no {CENSUS}; run `python -m harness matrix {producer} --census`"
        ]
    if (document["package"], document["since"], document["probes"]) != (
        matrix.package,
        matrix.since,
        list(matrix.probes),
    ):
        problems.append(
            f"{producer}: the census was taken for another window or probe; retake it"
        )
    problems += [f"{producer}: {p}" for p in census.coverage(matrix, document)]
    by_release = {(e["version"], e["profile"]): e for e in document["releases"]}
    for variant in matrix.variants:
        entry = by_release.get((variant.version, variant.profile)) or {}
        for mode in matrix.modes:
            for scenario in variant.scenarios:
                if scenario in variant.withheld:
                    continue
                directory = fixture_dir(producer, mode, variant, scenario)
                if not any(directory.glob("req-*")):
                    problems.append(
                        f"{producer}/{variant.mode(mode)}/{scenario}: not recorded"
                    )
        probes = [fixture_dir(producer, "native", variant, p) for p in matrix.probes]
        if (
            "native" in matrix.modes
            and not set(matrix.probes) & set(variant.withheld)
            and entry.get("shape")
            and all(any(d.glob("req-*")) for d in probes)
        ):
            lines = sorted(
                f"{p} {line}"
                for p, d in zip(matrix.probes, probes)
                for line in shape(d)
            )
            if (found := digest(lines)) != entry["shape"]:
                problems.append(
                    f"{producer}/{variant.mode('native')}: probe shape {found}, census says "
                    f"{entry['shape']}; re-record the variant or retake the census"
                )
    return problems


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        prog="python -m harness matrix", description=__doc__.split("\n\n")[0]
    )
    parser.add_argument("producer", nargs="?")
    parser.add_argument(
        "variant", nargs="*", help="variant names; default: all of them"
    )
    parser.add_argument(
        "--scenario", action="append", default=[], help="limit to these scenarios"
    )
    parser.add_argument(
        "--census",
        action="store_true",
        help="classify every release (needs the network)",
    )
    parser.add_argument(
        "--check", action="store_true", help="offline coverage and freshness check"
    )
    parser.add_argument(
        "--list", action="store_true", help="print each suite's variants"
    )
    parser.add_argument(
        "--support-rows",
        action="store_true",
        help="print the fixtures README rows of versioned modes",
    )
    parser.add_argument(
        "--jobs", type=int, default=2, help="environments built ahead by --census"
    )
    parser.add_argument(
        "--retry", action="store_true", help="--census: run only unclassified releases"
    )
    parser.add_argument(
        "--live",
        action="store_true",
        help="record the [[recording]] releases' own cassettes on Bedrock (variant: release versions)",
    )
    args = parser.parse_args(argv)
    known = matrices()
    if args.producer and args.producer not in known:
        raise SystemExit(
            f"no versions.toml for {args.producer!r}; suites with one: {', '.join(known)}"
        )
    selected = {args.producer: known[args.producer]} if args.producer else known
    if args.list:
        for producer, (_, matrix) in selected.items():
            print(
                f"{producer}: {matrix.package} since {matrix.since}, probes {list(matrix.probes)}"
            )
            for variant in matrix.variants:
                print(f"  {variant.name:<28} {variant.doc.splitlines()[0][:100]}")
        return
    if args.support_rows:
        for producer in selected:
            print("\n".join(support_rows(producer)))
        return
    if args.check:
        problems = [
            p for producer, (_, m) in selected.items() for p in check(producer, m)
        ]
        for problem in problems:
            print(f"[matrix] {problem}")
        if problems:
            raise SystemExit(1)
        print(
            f"[matrix] {len(selected)} suite(s): every release of the window is held by a variant"
        )
        return
    if not args.producer:
        raise SystemExit("name a producer, or pass --check or --list")
    suite, matrix = selected[args.producer]
    if args.live:
        failed = record_live(suite, matrix, args.variant)
        if failed:
            raise SystemExit("[matrix] failed: " + ", ".join(failed))
        print(
            f"[matrix] next: python -m harness matrix {args.producer} --census --retry"
        )
        return
    if args.census:
        census.run(matrix, suite, jobs=args.jobs, retry=args.retry)
        problems = census.coverage(matrix, census_of(matrix) or {"releases": []})
        for problem in problems:
            print(f"[census] {problem}")
        return
    failed = record(args.producer, suite, matrix, args.variant, args.scenario)
    if failed:
        raise SystemExit("[matrix] failed: " + ", ".join(failed))
    print(
        "[matrix] next: UPDATE_GOLDENS=1 cargo nextest run --locked -p sideseat-server --test "
        "message_goldens -E 'test(=message_goldens)', then python -m harness truth "
        f"{args.producer} (the truth lists every fixture of a scenario)"
    )
