import type { ColDef } from "ag-grid-community";
import { formatTimestamp24h, formatDuration, formatCost, formatTokens } from "@/lib/format";
import type { SpanSummary } from "@/api/otel/types";
import type { ColumnConfig } from "@/components/column-selector";
import {
  FavoriteCellRenderer,
  TokensCellRenderer,
  CostCellRenderer,
  ActionsCellRenderer,
} from "@/components/grid";

export const defaultColDef: ColDef<SpanSummary> = {
  resizable: true,
  sortable: false,
  sortingOrder: ["asc", "desc"],
  flex: 1,
  cellStyle: { fontVariantNumeric: "tabular-nums" },
};

export const DEFAULT_VISIBLE_COLUMNS: readonly string[] = [
  "timestamp_start",
  "span_name",
  "observation_type",
  "duration_ms",
  "tokens",
  "total_cost",
];

export const HIDEABLE_COLUMNS: readonly ColumnConfig[] = [
  { id: "timestamp_start", label: "Timestamp" },
  { id: "span_name", label: "Name" },
  { id: "observation_type", label: "Type" },
  { id: "duration_ms", label: "Latency" },
  { id: "tokens", label: "Tokens" },
  { id: "total_cost", label: "Total Cost" },
  { id: "trace_id", label: "Trace ID" },
  { id: "span_id", label: "Span ID" },
  { id: "session_id", label: "Session" },
  { id: "user_id", label: "User" },
  { id: "environment", label: "Environment" },
  { id: "framework", label: "Framework" },
  { id: "status_code", label: "Status" },
  { id: "gen_ai_system", label: "Provider" },
  { id: "agent_name", label: "Agent" },
  { id: "input_cost", label: "Input Cost" },
  { id: "output_cost", label: "Output Cost" },
  { id: "cache_read_cost", label: "Cache Read Cost" },
  { id: "cache_write_cost", label: "Cache Write Cost" },
  { id: "reasoning_cost", label: "Reasoning Cost" },
  { id: "input_tokens", label: "Input Tokens" },
  { id: "output_tokens", label: "Output Tokens" },
  { id: "cache_read_tokens", label: "Cache Read Tokens" },
  { id: "cache_write_tokens", label: "Cache Write Tokens" },
  { id: "reasoning_tokens", label: "Reasoning Tokens" },
];

export const NON_HIDEABLE_COLUMNS = new Set(["favorite", "actions"]);

export const columnDefs: ColDef<SpanSummary>[] = [
  {
    colId: "favorite",
    headerName: "",
    width: 26,
    minWidth: 26,
    maxWidth: 26,
    sortable: false,
    resizable: false,
    flex: 0,
    cellRenderer: FavoriteCellRenderer,
    cellStyle: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      padding: 0,
      marginLeft: -8,
    },
  },
  {
    colId: "timestamp_start",
    field: "timestamp_start",
    headerName: "Timestamp",
    minWidth: 190,
    sortable: true,
    sort: "desc",
    valueFormatter: (p) => formatTimestamp24h(p.value),
    cellStyle: { paddingLeft: 0, marginLeft: -6, fontVariantNumeric: "tabular-nums" },
  },
  {
    colId: "span_name",
    field: "span_name",
    headerName: "Name",
    minWidth: 200,
    valueFormatter: (p) => p.value || "-",
  },
  {
    colId: "observation_type",
    field: "observation_type",
    headerName: "Type",
    minWidth: 100,
    valueFormatter: (p) => p.value || "-",
  },
  {
    colId: "duration_ms",
    field: "duration_ms",
    headerName: "Latency",
    minWidth: 120,
    sortable: true,
    valueFormatter: (p) => formatDuration(p.value),
  },
  {
    colId: "tokens",
    headerName: "Tokens",
    minWidth: 200,
    cellRenderer: TokensCellRenderer,
  },
  {
    colId: "total_cost",
    field: "total_cost",
    headerName: "Total Cost",
    minWidth: 120,
    sortable: true,
    cellRenderer: CostCellRenderer,
  },
  {
    colId: "trace_id",
    field: "trace_id",
    headerName: "Trace ID",
    minWidth: 280,
    valueFormatter: (p) => p.value,
  },
  {
    colId: "span_id",
    field: "span_id",
    headerName: "Span ID",
    minWidth: 160,
    valueFormatter: (p) => p.value,
  },
  {
    colId: "session_id",
    field: "session_id",
    headerName: "Session",
    minWidth: 120,
    valueFormatter: (p) => p.value || "-",
  },
  {
    colId: "user_id",
    field: "user_id",
    headerName: "User",
    minWidth: 120,
    valueFormatter: (p) => p.value || "-",
  },
  {
    colId: "environment",
    field: "environment",
    headerName: "Environment",
    minWidth: 120,
    valueFormatter: (p) => p.value || "-",
  },
  {
    colId: "framework",
    field: "framework",
    headerName: "Framework",
    minWidth: 120,
    valueFormatter: (p) => p.value || "-",
  },
  {
    colId: "status_code",
    field: "status_code",
    headerName: "Status",
    minWidth: 100,
    valueFormatter: (p) => p.value || "-",
  },
  {
    colId: "gen_ai_system",
    field: "gen_ai_system",
    headerName: "Provider",
    minWidth: 120,
    valueFormatter: (p) => p.value || "-",
  },
  {
    colId: "agent_name",
    field: "agent_name",
    headerName: "Agent",
    minWidth: 120,
    valueFormatter: (p) => p.value || "-",
  },
  {
    colId: "input_cost",
    field: "input_cost",
    headerName: "Input Cost",
    minWidth: 100,
    valueFormatter: (p) => formatCost(p.value),
  },
  {
    colId: "output_cost",
    field: "output_cost",
    headerName: "Output Cost",
    minWidth: 100,
    valueFormatter: (p) => formatCost(p.value),
  },
  {
    colId: "cache_read_cost",
    field: "cache_read_cost",
    headerName: "Cache Read Cost",
    minWidth: 120,
    valueFormatter: (p) => formatCost(p.value),
  },
  {
    colId: "cache_write_cost",
    field: "cache_write_cost",
    headerName: "Cache Write Cost",
    minWidth: 120,
    valueFormatter: (p) => formatCost(p.value),
  },
  {
    colId: "reasoning_cost",
    field: "reasoning_cost",
    headerName: "Reasoning Cost",
    minWidth: 120,
    valueFormatter: (p) => formatCost(p.value),
  },
  {
    colId: "input_tokens",
    field: "input_tokens",
    headerName: "Input Tokens",
    minWidth: 100,
    valueFormatter: (p) => formatTokens(p.value),
  },
  {
    colId: "output_tokens",
    field: "output_tokens",
    headerName: "Output Tokens",
    minWidth: 100,
    valueFormatter: (p) => formatTokens(p.value),
  },
  {
    colId: "cache_read_tokens",
    field: "cache_read_tokens",
    headerName: "Cache Read Tokens",
    minWidth: 100,
    valueFormatter: (p) => formatTokens(p.value),
  },
  {
    colId: "cache_write_tokens",
    field: "cache_write_tokens",
    headerName: "Cache Write Tokens",
    minWidth: 100,
    valueFormatter: (p) => formatTokens(p.value),
  },
  {
    colId: "reasoning_tokens",
    field: "reasoning_tokens",
    headerName: "Reasoning Tokens",
    minWidth: 100,
    valueFormatter: (p) => formatTokens(p.value),
  },
  {
    colId: "actions",
    headerName: "Actions",
    minWidth: 96,
    width: 96,
    maxWidth: 120,
    sortable: false,
    resizable: false,
    cellRenderer: ActionsCellRenderer,
    cellStyle: { display: "flex", alignItems: "center", justifyContent: "center", padding: 0 },
  },
];

export const rowSelectionConfig = {
  mode: "multiRow" as const,
  headerCheckbox: true,
  checkboxes: true,
  enableClickSelection: false,
};
