[package]
name = "sideseat-adapter-pricing"
version.workspace = true
license = "Apache-2.0"
publish = false
edition = "2024"
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
sideseat-ports = { path = "../ports" }
async-trait = { workspace = true }
reqwest = { workspace = true }
